finance_app/urls.py
from django.views.generic import RedirectView
from django.urls import path 
from . import views

app_name = 'finance_app'

urlpatterns = [
    path('', RedirectView.as_view(url='dashboard'), name='dashboard'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('register', views.register, name='register'),
    path('dashboard', views.DashboardApp.as_view(), name='dashboard'),
    path('extract', views.ExtractApp.as_view(), name='extract'),
    path('about', views.AboutApp.as_view(), name='about'),
    path('createearnings', views.create_earnings, name='createearnings'),
    path('createexpenses', views.create_expenses, name='createexpenses'),
    path('createcategoryearnings', views.create_category_earnings, name='createcategoryearnings'),
    path('createcategoryexpenses', views.create_category_expenses, name='createcategoryexpenses'),
    path('deletecategoryearnings', views.delete_category_earnings, name='deletecategoryearnings'),
    path('deletecategoryexpenses', views.delete_category_expenses, name='deletecategoryexpenses'),
    path('deleteearnings/<int:id>', views.delete_earnings, name='deleteearnings'),
    path('deleteexpenses/<int:id>', views.delete_expenses, name='deleteexpenses'),
    path('updateearnings/<int:id>', views.update_earnings, name='updateearnings'),
    path('updateexpenses/<int:id>', views.update_expenses, name='updateexpenses'),
]

personal_finance_control/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static 

admin.site.site_header = 'Gestor de Finanças'
admin.site.site_title = "Gestor de Finanças"
admin.site.index_title = "Bem-vindo ao painel de administração"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('finance_app.urls', namespace='finance_app')),
]

if settings.DEBUG: 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

finance_app/views/about.py
from django.shortcuts import render
from django.views.generic import View
from django.shortcuts import redirect

class AboutApp(View):
    template_name = 'finance_app/about.html'
    
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            # Redireciona o usuário para a página de login
            return redirect('/login')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

finance_app/views/createviews.py
from django.http import HttpResponseRedirect
from finance_app.models import CategoryEarnings, CategoryExpenses, Earnings, Expenses, UniqueID
from django.contrib import messages
import decimal
from django.shortcuts import redirect
from django.contrib.auth.models import User

def convert_value(value: str):

    if ',' in value:
        value = value.replace('.', '').replace(',', '.')
    else:
        value = value.replace(',', '')

    value_decimal = decimal.Decimal(value)
    value_decimal = value_decimal.quantize(decimal.Decimal('0.00'))

    return float(value_decimal)

def create_earnings(request):

    if not request.user.is_authenticated:
        # Redireciona o usuário para a página de login
        return redirect('/login')
    
    if request.method == 'POST':
        unique_id = UniqueID.objects.create()
        description = request.POST.get('description')
        value = convert_value(request.POST.get('value'))
        date = request.POST.get('date')
        recurrent = request.POST.get('recurrent')
        category = CategoryEarnings.objects.get(
            id=int(request.POST.get('category')
            )
        )
        user = request.user


        earning = Earnings(unique=unique_id, description=description, value=value, date=date, recurrence=int(recurrent), category=category, user=user)
        earning.save()

        messages.success(request, 'Receita adicionada com sucesso!')
        return HttpResponseRedirect('/dashboard')

def create_expenses(request):

    if not request.user.is_authenticated:
        # Redireciona o usuário para a página de login
        return redirect('/login')
    
    if request.method == 'POST':
        unique_id = UniqueID.objects.create()
        description = request.POST.get('description')
        value = convert_value(request.POST.get('value'))
        date = request.POST.get('date')
        recurrent = request.POST.get('recurrent')
        category = CategoryExpenses.objects.get(
            id=int(request.POST.get('category')
            )
        )
        user = request.user
        
        expense = Expenses(unique=unique_id, description=description, value=value, date=date, recurrence=int(recurrent), category=category, user=user)
        expense.save()

        messages.success(request, 'Despesa adicionada com sucesso!')
        return HttpResponseRedirect('/dashboard')
    
def create_category_earnings(request):

    if not request.user.is_authenticated:
        # Redireciona o usuário para a página de login
        return redirect('/login')
    
    if request.method == 'POST':
        description = request.POST.get('description')
        category = CategoryEarnings(name=description, user=request.user)
        category.save()

        messages.success(request, 'Categoria de receita adicionada com sucesso!')
        return HttpResponseRedirect('/dashboard')
    
def create_category_expenses(request):

    if not request.user.is_authenticated:
        # Redireciona o usuário para a página de login
        return redirect('/login')
    
    if request.method == 'POST':
        description = request.POST.get('description')
        category = CategoryExpenses(name=description, user=request.user)
        category.save()

        messages.success(request, 'Categoria de despesa adicionada com sucesso!')
        return HttpResponseRedirect('/dashboard')

finance_app/views/dashboard.py
from django.views.generic import ListView
from finance_app.models import CategoryEarnings, CategoryExpenses, Earnings, Expenses
import decimal
from datetime import datetime
import json
from django.db.models import Sum
from django.db.models import QuerySet
from django.shortcuts import redirect
from django.contrib.auth.models import User


class DashboardApp(ListView):
    template_name = 'finance_app/dashboard.html'
    model = Earnings

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            # Redireciona o usuário para a página de login
            return redirect('/login')
        return super().dispatch(request, *args, **kwargs)

    def get_sums_data_and_labels(self, earnings: QuerySet, expenses: QuerySet, start_date: str, end_date: str):
        # Passanso a data de string para datetime e pegando a quantidade de meses
        start_date = datetime.strptime(start_date, '%Y-%m-%d')
        end_date = datetime.strptime(end_date, '%Y-%m-%d')
        months = (end_date.year - start_date.year) * 12 + (end_date.month - start_date.month)
        
        # Mapeamento dos nomes dos meses em português
        month_names = {
            1: 'Janeiro',
            2: 'Fevereiro',
            3: 'Março',
            4: 'Abril',
            5: 'Maio',
            6: 'Junho',
            7: 'Julho',
            8: 'Agosto',
            9: 'Setembro',
            10: 'Outubro',
            11: 'Novembro',
            12: 'Dezembro'
        }
        # Pegando os dados dos ganhos e gastos referente ao período e os labels
        labels = []
        earnings_sum = []
        expenses_sum = []

        for i in range(months + 1):
            month = (start_date.month + i) % 12
            if month == 0:
                month = 12
            month_name = month_names[month]
            labels.append(month_name)

            earnings_month_sum = earnings.filter(date__month=month).aggregate(total=Sum('value'))['total'] or 0
            earnings_sum.append(int(earnings_month_sum))

            expenses_month_sum = expenses.filter(date__month=month).aggregate(total=Sum('value'))['total'] or 0
            expenses_sum.append(int(expenses_month_sum))

        return labels, earnings_sum, expenses_sum
    
    def get_data_based_on_category(self, user_id, earnings: QuerySet, expenses: QuerySet, start_date: str, end_date: str, filters_category_earnings: list, filters_category_expenses: list):
        
        # Verificando a necessidade de filtrar por categoria
        if not filters_category_earnings and not filters_category_expenses:
            categoryEarnings = list(CategoryEarnings.objects.values_list('name', flat=True).filter(user_id=user_id))
            categoryExpenses = list(CategoryExpenses.objects.values_list('name', flat=True).filter(user_id=user_id))
        else:
            if filters_category_earnings and filters_category_expenses:
                categoryEarnings = list(CategoryEarnings.objects.filter(id__in=filters_category_earnings, user_id=user_id).values_list('name', flat=True))
                categoryExpenses = list(CategoryExpenses.objects.filter(id__in=filters_category_expenses, user_id=user_id).values_list('name', flat=True))
            elif filters_category_earnings:
                categoryEarnings = list(CategoryEarnings.objects.filter(id__in=filters_category_earnings, user_id=user_id).values_list('name', flat=True))
                categoryExpenses = list(CategoryExpenses.objects.values_list('name', flat=True).filter(user_id=user_id))
            elif filters_category_expenses:
                categoryEarnings = list(CategoryEarnings.objects.values_list('name', flat=True).filter(user_id=user_id))
                categoryExpenses = list(CategoryExpenses.objects.filter(id__in=filters_category_expenses, user_id=user_id).values_list('name', flat=True))

        dataEarning = []
        dataExpenses = []

        for category in categoryEarnings:
            category_sum = earnings.filter(category__name=category, date__range=[start_date, end_date]).aggregate(total=Sum('value'))['total'] or 0
            dataEarning.append(int(category_sum))

        for category in categoryExpenses:
            category_sum = expenses.filter(category__name=category, date__range=[start_date, end_date]).aggregate(total=Sum('value'))['total'] or 0
            dataExpenses.append(int(category_sum))
        
        return (
                json.dumps(categoryExpenses), 
                json.dumps(categoryEarnings), 
                json.dumps(dataEarning), 
                json.dumps(dataExpenses)
            )

    def get_context_data(self, **kwargs):
        # Feito e comentado por: Jean Carlos
        context = super().get_context_data(**kwargs)
        user_id = self.request.user.id

        context['categoryearnings'] = CategoryEarnings.objects.filter(user_id=user_id)
        context['categoryexpenses'] = CategoryExpenses.objects.filter(user_id=user_id)
        context['username'] = self.request.user.first_name + ' ' + self.request.user.last_name
        

        # Pegando a data de início e fim passada pelo usuário
        user_start_date = self.request.GET.get('start_date')
        user_end_date = self.request.GET.get('end_date')

        # Pegando a data de início e fim do ano atual, caso não seja passado pelo usuário
        if user_start_date or user_end_date:
            start_date = user_start_date 
            end_date = user_end_date
        else:
            start_date = datetime.strftime(datetime(datetime.now().year, 1, 1).date(), '%Y-%m-%d')
            end_date = datetime.strftime(datetime(datetime.now().year, 12, 31).date(), '%Y-%m-%d')
        
        # Passando a data para o template
        context['start_date'] = start_date
        context['end_date'] = end_date

        # Dados dos ganhos e gastos referente ao período
        earnings = Earnings.objects.filter(date__range=[start_date, end_date], user_id=user_id)
        expenses = Expenses.objects.filter(date__range=[start_date, end_date], user_id=user_id)

        context['earnings_and_expenses'] = earnings.union(expenses).order_by('-unique_id')
        
        if self.request.method == 'GET':
            filters_category_earnings = self.request.GET.getlist('categoryEarnings')
            filters_category_expenses = self.request.GET.getlist('categoryExpenses')

            if filters_category_earnings:
                earnings = earnings.filter(category__id__in=filters_category_earnings)
            if filters_category_expenses:
                expenses = expenses.filter(category__id__in=filters_category_expenses)


        # Pegando os dados dos ganhos e gastos referente ao período e os labels
        labels, earnings_sum, expenses_sum = self.get_sums_data_and_labels(earnings, expenses, start_date, end_date)   

        # Passando os dados para json, para serem usados no gráfico
        labels = json.dumps(labels)
        earnings_sum = json.dumps(earnings_sum)
        expenses_sum = json.dumps(expenses_sum)
        
        # Passando os dados para o template
        context['labels'] = labels
        context['earnings_list'] = earnings_sum
        context['expenses_list'] = expenses_sum

        # Dados para o resumo do período
        context['sum_earnings'] = decimal.Decimal(earnings.aggregate(total=Sum('value'))['total'] or 0).quantize(decimal.Decimal('0.00'))
        context['sum_expenses'] = decimal.Decimal(expenses.aggregate(total=Sum('value'))['total'] or 0).quantize(decimal.Decimal('0.00'))
        context['balance'] = (context['sum_earnings'] - context['sum_expenses']).quantize(decimal.Decimal('0.00'))
        
        # Dados para o gráfico de pizza
        categoryExpenses, categoryEarnings, data_earnings_category, data_expenses_category = self.get_data_based_on_category(
            user_id,
            earnings, 
            expenses, 
            start_date, 
            end_date,
            filters_category_earnings,
            filters_category_expenses
        )

        context['category_earnings'] = categoryEarnings
        context['category_expenses'] = categoryExpenses
        context['data_earnings_category'] = data_earnings_category
        context['data_expenses_category'] = data_expenses_category

        return context

finance_app/views/deleteviews.py
from django.http import HttpResponseRedirect
from finance_app.models import CategoryEarnings, CategoryExpenses, Earnings, Expenses
from django.contrib import messages
from django.contrib.auth.models import User
from django.shortcuts import redirect

def delete_category_earnings(request):
    if not request.user.is_authenticated:
        # Redireciona o usuário para a página de login
        return redirect('/login')
    
    if request.method == 'POST':
        category = request.POST.get('delete-category')
        category = CategoryEarnings.objects.get(id=int(category))
        category.delete()

        messages.success(request, 'Categoria de receita deletada com sucesso!')
        return HttpResponseRedirect('/dashboard')

def delete_category_expenses(request):
    if not request.user.is_authenticated:
        # Redireciona o usuário para a página de login
        return redirect('/login')
    
    if request.method == 'POST':
        category = request.POST.get('delete-category')
        category = CategoryExpenses.objects.get(id=int(category))
        category.delete()

        messages.success(request, 'Categoria de despesa deletada com sucesso!')
        return HttpResponseRedirect('/dashboard')
    
def delete_earnings(request, id):
    
    if not request.user.is_authenticated:
        # Redireciona o usuário para a página de login
        return redirect('/login')
    
    earning = Earnings.objects.get(id=int(id))
    earning.delete()

    messages.success(request, 'Receita deletada com sucesso!')
    return HttpResponseRedirect('/extract')

def delete_expenses(request, id):

    if not request.user.is_authenticated:
        # Redireciona o usuário para a página de login
        return redirect('/login')
    
    expense = Expenses.objects.get(id=int(id))
    expense.delete()

    messages.success(request, 'Despesa deletada com sucesso!')
    return HttpResponseRedirect('/extract')

finance_app/views/login.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect

def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/dashboard')  # Redireciona para a página inicial após o login
        else:
            error_message = 'Credenciais inválidas. Tente novamente.'
            return render(request, 'finance_app/login.html', {'error_message': error_message})
    return render(request, 'finance_app/login.html')

def logout_view(request):
    logout(request)
    return redirect('/login') 

finance_app/templates/finance_app/index.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">

<head>
    {% csrf_token %}
    <title>{% block title %}{% endblock %}</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome-free-6.4.0-web/css/all.min.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="shortcut icon" href="https://cdn-icons-png.flaticon.com/512/4891/4891497.png" type="image/x-icon">
    {% block styles %}{% endblock %}
</head>

<body>
    <!-- barra de navegação -->
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: rgb(71, 2, 71);">
        <a class="navbar-brand text-white" href="{% url 'finance_app:dashboard' %}">
            <i class="fas fa-landmark mr-1"></i>
            CONTROLE DE <strong>FINANÇAS PESSOAIS</strong>
        </a>
        <div class="collapse navbar-collapse" id="conteudoNavbarSuportado">
            <ul class="navbar-nav mr-auto"></ul>
            <button id="dark-mode-toggle" class="btn btn-dark mr-3">
                <i class="fas fa-moon" id="dl-icon"></i>
            </button>
            {% block contentnav %}{% endblock %}
        </div>
    </nav>

    <!-- sidebar and content -->
    <div class="container-fluid">
        <div class="row">
            <!-- barra de navegação lateral -->
            <div class="col-md-2 sidebar-class p-0">
                <div class="sidebar d-flex flex-column flex-shrink-0 p-3 container-fluid">
                    <div class="row mb-3">
                        <div class="col d-flex justify-content-center">
                            <div class="rounded-circle">
                                <img src="https://img.freepik.com/vetores-premium/controle-financeiro_36900-2119.jpg"
                                    alt=""
                                    style="width: 100%; height: 100%; object-fit: cover; object-position: center;">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col username text-center mb-2">
                            <h6 class="user-name">
                                Olá, {{ username }}!
                            </h6>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col">
                            <div class="d-flex justify-content-between">
                                <button type="button" id="add-revenue" class="btn btn-outline-success btn-md">
                                    <i class="fa-solid fa-plus"></i>
                                    Receita
                                </button>
                                <button type="button" id="add-expense" class="btn btn-outline-danger btn-md">
                                    <i class="fa-solid fa-plus"></i>
                                    Despesa
                                </button>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="row mb-auto">
                        <div class="col">
                            <ul class="nav nav-pills flex-column mt-1">
                                <li>
                                    <a href="{% url 'finance_app:dashboard' %}" class="nav-link" id="dashboard">
                                        <i class="fa-solid fa-gauge"></i>
                                        Início
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'finance_app:extract' %}" class="nav-link" id="extract">
                                        <i class="fa-solid fa-clipboard-list"></i>
                                        Extrato
                                    </a>
                                </li>
                                <li>
                                    <!-- sobre -->
                                    <a href="{% url 'finance_app:about' %}" class="nav-link" id="about">
                                        <i class="fa-solid fa-info-circle"></i>
                                        Sobre
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col">
                            <a href="{% url 'finance_app:logout' %}" class="nav-link text-body pb-0">
                                <i class="fas fa-sign-out"></i>
                                Sair
                            </a>
                        </div>
                    </div>
                </div>
            </div>

            <!-- conteúdo -->
            <div class="col-md-10 container-fluid pl-0">
                {% block nav %}{% endblock %}
                <div class="container">
                    {% if messages %}
                    <div class="alert alert-success alert-dismissible fade show mt-2" role="alert">
                        {% for message in messages %}
                        {{ message }}
                        {% endfor %}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">x</span>
                        </button>
                    </div>
                    {% endif %}
                    {% block content %}{% endblock %}
                </div>
            </div>
        </div>
    </div>
    <!-- modal -->
    {% include 'finance_app/includes/modal-index.html' %}
    {% block modal %}{% endblock %}
</body>
<!-- bootstrap -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.6/dist/umd/popper.min.js"
    integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.2.1/dist/js/bootstrap.min.js"
    integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
    crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/admin-lte@3.1/dist/js/adminlte.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/admin-lte@3.1/dist/css/adminlte.min.css">
<!-- scripts -->
<script src="{% static 'js/main.js' %}"></script>
<script>
    setTimeout(function () {
        $(".alert").alert('close');
    }, 3000);
</script>
<script>
    function toggleDarkMode() {
        const body = document.body;
        body.classList.toggle("dark-mode");

        const isDarkModeEnabled = body.classList.contains("dark-mode");

        localStorage.setItem("darkModeEnabled", isDarkModeEnabled);
    }

    window.addEventListener("load", function () {
        const isDarkModeEnabled = localStorage.getItem("darkModeEnabled");

        if (isDarkModeEnabled === "true") {
            const body = document.body;
            body.classList.add("dark-mode");
        }
    });
</script>
<script>
    const myButton = document.getElementById("dark-mode-toggle");
    const icon = document.getElementById("dl-icon")
    myButton.addEventListener("click", function () {
        icon.classList.toggle('fa-moon');
        icon.classList.toggle('fa-sun');
    })
    myButton.addEventListener("click", toggleDarkMode)
</script>
{% block scripts %}{% endblock %}

</html>

finance_app/templates/finance_app/login.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    {% csrf_token %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login - Gestor de Finanças</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="static/css/base.css">
    <style>
        .admin-button {
            position: fixed;
            top: 10px;
            right: 10px;
            z-index: 9999;
        }
    </style>
</head>

<body>
    <div class="container mt-4">
        <div class="row align-items-center" style="min-height: calc(100vh - 56px);">
            <div class="col-md-10 mx-auto col-lg-5">
                <form class="p-4 p-md-5 border rounded-3 bg-light" action="{% url 'finance_app:login' %}" method="POST">
                    {% csrf_token %}
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" id="usernameInput" placeholder="Usuário" name="username"
                            required />
                        <label for="usernameInput">Usuário</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="password" class="form-control" id="inputPassword" placeholder="Senha"
                            name="password" required />
                        <label for="inputPassword">Senha</label>
                    </div>
                    <button class="btn btn-lg btn-success mb-3 w-100" type="submit">Login</button>
                    <div class="register text-center">
                        <label>
                            <small>
                                Não tem uma conta? <a href="{% url 'finance_app:register' %}">Cadastre-se</a>
                            </small>
                        </label>
                    </div>
                </form>

                <!-- Botão discreto fixado no canto superior direito -->
                <div class="admin-button">
                    <a href="{% url 'admin:index' %}" class="btn btn-outline-primary btn-sm">Admin</a>
                </div>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>

finance_app/templates/finance_app/register.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    {% csrf_token %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastre-se - Gestor de Finanças</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="static/css/base.css">
</head>

<body>
    <div class="container mt-4">
        <div class="row align-items-center" style="min-height: calc(100vh - 56px);">
            <div class="col-md-10 mx-auto col-lg-5">
                <form class="p-4 p-md-5 border rounded-3 bg-light" action="{% url 'finance_app:register' %}"
                    method="POST">
                    {% csrf_token %}

                    {% if error_message %}
                    <div class="alert alert-danger" role="alert">
                        {{ error_message }}
                    </div>
                    {% endif %}

                    <div class="form-floating mb-3">
                        <input type="email" class="form-control" id="inputEmail" placeholder="E-mail" name="email"
                            value="{{ email }}" required />
                        <label for="inputEmail">E-mail</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" id="inputName" placeholder="Nome" name="name"
                            value="{{ first_name }}" required />
                        <label for="inputName">Nome</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" id="inputLastName" placeholder="Sobrenome"
                            value="{{ last_name }}" name="lastname" required />
                        <label for="inputLastName">Sobrenome</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="user" class="form-control" id="inputUser" placeholder="Usuário" name="username"
                            value="{{ username }}" required />
                        <label for="inputUser">Usuário</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="password" class="form-control" id="inputPassword" placeholder="Senha"
                            name="password" required />
                        <label for="inputPassword">Senha</label>
                    </div>
                    <button class="btn btn-lg btn-outline-success mb-3 w-100" type="submit">Cadastre-se</button>
                    <div class="register text-center">
                        <label>
                            <small>
                                Já tem uma conta? <a href="{% url 'finance_app:login' %}">Faça o login</a>
                            </small>
                        </label>
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

</html>