finance_app/urls.py
from django.views.generic import RedirectView
from django.urls import path 
from . import views

app_name = 'finance_app'

urlpatterns = [
    path('', RedirectView.as_view(url='dashboard'), name='dashboard'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('register', views.register, name='register'),
    path('dashboard', views.DashboardApp.as_view(), name='dashboard'),
    path('extract', views.ExtractApp.as_view(), name='extract'),
    path('about', views.AboutApp.as_view(), name='about'),
    path('createearnings', views.create_earnings, name='createearnings'),
    path('createexpenses', views.create_expenses, name='createexpenses'),
    path('createcategoryearnings', views.create_category_earnings, name='createcategoryearnings'),
    path('createcategoryexpenses', views.create_category_expenses, name='createcategoryexpenses'),
    path('deletecategoryearnings', views.delete_category_earnings, name='deletecategoryearnings'),
    path('deletecategoryexpenses', views.delete_category_expenses, name='deletecategoryexpenses'),
    path('deleteearnings/<int:id>', views.delete_earnings, name='deleteearnings'),
    path('deleteexpenses/<int:id>', views.delete_expenses, name='deleteexpenses'),
    path('updateearnings/<int:id>', views.update_earnings, name='updateearnings'),
    path('updateexpenses/<int:id>', views.update_expenses, name='updateexpenses'),
]

personal_finance_control/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static 

admin.site.site_header = 'Gestor de Finanças'
admin.site.site_title = "Gestor de Finanças"
admin.site.index_title = "Bem-vindo ao painel de administração"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('finance_app.urls', namespace='finance_app')),
]

if settings.DEBUG: 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

finance_app/views/about.py
from django.shortcuts import render
from django.views.generic import View
from django.shortcuts import redirect

class AboutApp(View):
    template_name = 'finance_app/about.html'
    
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            # Redireciona o usuário para a página de login
            return redirect('/login')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

finance_app/views/createviews.py
from django.http import HttpResponseRedirect
from finance_app.models import CategoryEarnings, CategoryExpenses, Earnings, Expenses, UniqueID
from django.contrib import messages
import decimal
from django.shortcuts import redirect
from django.contrib.auth.models import User

def convert_value(value: str):

    if ',' in value:
        value = value.replace('.', '').replace(',', '.')
    else:
        value = value.replace(',', '')

    value_decimal = decimal.Decimal(value)
    value_decimal = value_decimal.quantize(decimal.Decimal('0.00'))

    return float(value_decimal)

def create_earnings(request):

    if not request.user.is_authenticated:
        # Redireciona o usuário para a página de login
        return redirect('/login')
    
    if request.method == 'POST':
        unique_id = UniqueID.objects.create()
        description = request.POST.get('description')
        value = convert_value(request.POST.get('value'))
        date = request.POST.get('date')
        recurrent = request.POST.get('recurrent')
        category = CategoryEarnings.objects.get(
            id=int(request.POST.get('category')
            )
        )
        user = request.user


        earning = Earnings(unique=unique_id, description=description, value=value, date=date, recurrence=int(recurrent), category=category, user=user)
        earning.save()

        messages.success(request, 'Receita adicionada com sucesso!')
        return HttpResponseRedirect('/dashboard')

def create_expenses(request):

    if not request.user.is_authenticated:
        # Redireciona o usuário para a página de login
        return redirect('/login')
    
    if request.method == 'POST':
        unique_id = UniqueID.objects.create()
        description = request.POST.get('description')
        value = convert_value(request.POST.get('value'))
        date = request.POST.get('date')
        recurrent = request.POST.get('recurrent')
        category = CategoryExpenses.objects.get(
            id=int(request.POST.get('category')
            )
        )
        user = request.user
        
        expense = Expenses(unique=unique_id, description=description, value=value, date=date, recurrence=int(recurrent), category=category, user=user)
        expense.save()

        messages.success(request, 'Despesa adicionada com sucesso!')
        return HttpResponseRedirect('/dashboard')
    
def create_category_earnings(request):

    if not request.user.is_authenticated:
        # Redireciona o usuário para a página de login
        return redirect('/login')
    
    if request.method == 'POST':
        description = request.POST.get('description')
        category = CategoryEarnings(name=description, user=request.user)
        category.save()

        messages.success(request, 'Categoria de receita adicionada com sucesso!')
        return HttpResponseRedirect('/dashboard')
    
def create_category_expenses(request):

    if not request.user.is_authenticated:
        # Redireciona o usuário para a página de login
        return redirect('/login')
    
    if request.method == 'POST':
        description = request.POST.get('description')
        category = CategoryExpenses(name=description, user=request.user)
        category.save()

        messages.success(request, 'Categoria de despesa adicionada com sucesso!')
        return HttpResponseRedirect('/dashboard')

finance_app/views/dashboard.py
from django.views.generic import ListView
from finance_app.models import CategoryEarnings, CategoryExpenses, Earnings, Expenses
import decimal
from datetime import datetime
import json
from django.db.models import Sum
from django.db.models import QuerySet
from django.shortcuts import redirect
from django.contrib.auth.models import User


class DashboardApp(ListView):
    template_name = 'finance_app/dashboard.html'
    model = Earnings

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            # Redireciona o usuário para a página de login
            return redirect('/login')
        return super().dispatch(request, *args, **kwargs)

    def get_sums_data_and_labels(self, earnings: QuerySet, expenses: QuerySet, start_date: str, end_date: str):
        # Passanso a data de string para datetime e pegando a quantidade de meses
        start_date = datetime.strptime(start_date, '%Y-%m-%d')
        end_date = datetime.strptime(end_date, '%Y-%m-%d')
        months = (end_date.year - start_date.year) * 12 + (end_date.month - start_date.month)
        
        # Mapeamento dos nomes dos meses em português
        month_names = {
            1: 'Janeiro',
            2: 'Fevereiro',
            3: 'Março',
            4: 'Abril',
            5: 'Maio',
            6: 'Junho',
            7: 'Julho',
            8: 'Agosto',
            9: 'Setembro',
            10: 'Outubro',
            11: 'Novembro',
            12: 'Dezembro'
        }
        # Pegando os dados dos ganhos e gastos referente ao período e os labels
        labels = []
        earnings_sum = []
        expenses_sum = []

        for i in range(months + 1):
            month = (start_date.month + i) % 12
            if month == 0:
                month = 12
            month_name = month_names[month]
            labels.append(month_name)

            earnings_month_sum = earnings.filter(date__month=month).aggregate(total=Sum('value'))['total'] or 0
            earnings_sum.append(int(earnings_month_sum))

            expenses_month_sum = expenses.filter(date__month=month).aggregate(total=Sum('value'))['total'] or 0
            expenses_sum.append(int(expenses_month_sum))

        return labels, earnings_sum, expenses_sum
    
    def get_data_based_on_category(self, user_id, earnings: QuerySet, expenses: QuerySet, start_date: str, end_date: str, filters_category_earnings: list, filters_category_expenses: list):
        
        # Verificando a necessidade de filtrar por categoria
        if not filters_category_earnings and not filters_category_expenses:
            categoryEarnings = list(CategoryEarnings.objects.values_list('name', flat=True).filter(user_id=user_id))
            categoryExpenses = list(CategoryExpenses.objects.values_list('name', flat=True).filter(user_id=user_id))
        else:
            if filters_category_earnings and filters_category_expenses:
                categoryEarnings = list(CategoryEarnings.objects.filter(id__in=filters_category_earnings, user_id=user_id).values_list('name', flat=True))
                categoryExpenses = list(CategoryExpenses.objects.filter(id__in=filters_category_expenses, user_id=user_id).values_list('name', flat=True))
            elif filters_category_earnings:
                categoryEarnings = list(CategoryEarnings.objects.filter(id__in=filters_category_earnings, user_id=user_id).values_list('name', flat=True))
                categoryExpenses = list(CategoryExpenses.objects.values_list('name', flat=True).filter(user_id=user_id))
            elif filters_category_expenses:
                categoryEarnings = list(CategoryEarnings.objects.values_list('name', flat=True).filter(user_id=user_id))
                categoryExpenses = list(CategoryExpenses.objects.filter(id__in=filters_category_expenses, user_id=user_id).values_list('name', flat=True))

        dataEarning = []
        dataExpenses = []

        for category in categoryEarnings:
            category_sum = earnings.filter(category__name=category, date__range=[start_date, end_date]).aggregate(total=Sum('value'))['total'] or 0
            dataEarning.append(int(category_sum))

        for category in categoryExpenses:
            category_sum = expenses.filter(category__name=category, date__range=[start_date, end_date]).aggregate(total=Sum('value'))['total'] or 0
            dataExpenses.append(int(category_sum))
        
        return (
                json.dumps(categoryExpenses), 
                json.dumps(categoryEarnings), 
                json.dumps(dataEarning), 
                json.dumps(dataExpenses)
            )

    def get_context_data(self, **kwargs):
        # Feito e comentado por: Jean Carlos
        context = super().get_context_data(**kwargs)
        user_id = self.request.user.id

        context['categoryearnings'] = CategoryEarnings.objects.filter(user_id=user_id)
        context['categoryexpenses'] = CategoryExpenses.objects.filter(user_id=user_id)
        context['username'] = self.request.user.first_name + ' ' + self.request.user.last_name
        

        # Pegando a data de início e fim passada pelo usuário
        user_start_date = self.request.GET.get('start_date')
        user_end_date = self.request.GET.get('end_date')

        # Pegando a data de início e fim do ano atual, caso não seja passado pelo usuário
        if user_start_date or user_end_date:
            start_date = user_start_date 
            end_date = user_end_date
        else:
            start_date = datetime.strftime(datetime(datetime.now().year, 1, 1).date(), '%Y-%m-%d')
            end_date = datetime.strftime(datetime(datetime.now().year, 12, 31).date(), '%Y-%m-%d')
        
        # Passando a data para o template
        context['start_date'] = start_date
        context['end_date'] = end_date

        # Dados dos ganhos e gastos referente ao período
        earnings = Earnings.objects.filter(date__range=[start_date, end_date], user_id=user_id)
        expenses = Expenses.objects.filter(date__range=[start_date, end_date], user_id=user_id)

        context['earnings_and_expenses'] = earnings.union(expenses).order_by('-unique_id')
        
        if self.request.method == 'GET':
            filters_category_earnings = self.request.GET.getlist('categoryEarnings')
            filters_category_expenses = self.request.GET.getlist('categoryExpenses')

            if filters_category_earnings:
                earnings = earnings.filter(category__id__in=filters_category_earnings)
            if filters_category_expenses:
                expenses = expenses.filter(category__id__in=filters_category_expenses)


        # Pegando os dados dos ganhos e gastos referente ao período e os labels
        labels, earnings_sum, expenses_sum = self.get_sums_data_and_labels(earnings, expenses, start_date, end_date)   

        # Passando os dados para json, para serem usados no gráfico
        labels = json.dumps(labels)
        earnings_sum = json.dumps(earnings_sum)
        expenses_sum = json.dumps(expenses_sum)
        
        # Passando os dados para o template
        context['labels'] = labels
        context['earnings_list'] = earnings_sum
        context['expenses_list'] = expenses_sum

        # Dados para o resumo do período
        context['sum_earnings'] = decimal.Decimal(earnings.aggregate(total=Sum('value'))['total'] or 0).quantize(decimal.Decimal('0.00'))
        context['sum_expenses'] = decimal.Decimal(expenses.aggregate(total=Sum('value'))['total'] or 0).quantize(decimal.Decimal('0.00'))
        context['balance'] = (context['sum_earnings'] - context['sum_expenses']).quantize(decimal.Decimal('0.00'))
        
        # Dados para o gráfico de pizza
        categoryExpenses, categoryEarnings, data_earnings_category, data_expenses_category = self.get_data_based_on_category(
            user_id,
            earnings, 
            expenses, 
            start_date, 
            end_date,
            filters_category_earnings,
            filters_category_expenses
        )

        context['category_earnings'] = categoryEarnings
        context['category_expenses'] = categoryExpenses
        context['data_earnings_category'] = data_earnings_category
        context['data_expenses_category'] = data_expenses_category

        return context

finance_app/views/deleteviews.py
from django.http import HttpResponseRedirect
from finance_app.models import CategoryEarnings, CategoryExpenses, Earnings, Expenses
from django.contrib import messages
from django.contrib.auth.models import User
from django.shortcuts import redirect

def delete_category_earnings(request):
    if not request.user.is_authenticated:
        # Redireciona o usuário para a página de login
        return redirect('/login')
    
    if request.method == 'POST':
        category = request.POST.get('delete-category')
        category = CategoryEarnings.objects.get(id=int(category))
        category.delete()

        messages.success(request, 'Categoria de receita deletada com sucesso!')
        return HttpResponseRedirect('/dashboard')

def delete_category_expenses(request):
    if not request.user.is_authenticated:
        # Redireciona o usuário para a página de login
        return redirect('/login')
    
    if request.method == 'POST':
        category = request.POST.get('delete-category')
        category = CategoryExpenses.objects.get(id=int(category))
        category.delete()

        messages.success(request, 'Categoria de despesa deletada com sucesso!')
        return HttpResponseRedirect('/dashboard')
    
def delete_earnings(request, id):
    
    if not request.user.is_authenticated:
        # Redireciona o usuário para a página de login
        return redirect('/login')
    
    earning = Earnings.objects.get(id=int(id))
    earning.delete()

    messages.success(request, 'Receita deletada com sucesso!')
    return HttpResponseRedirect('/extract')

def delete_expenses(request, id):

    if not request.user.is_authenticated:
        # Redireciona o usuário para a página de login
        return redirect('/login')
    
    expense = Expenses.objects.get(id=int(id))
    expense.delete()

    messages.success(request, 'Despesa deletada com sucesso!')
    return HttpResponseRedirect('/extract')

finance_app/views/login.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect

def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/dashboard')  # Redireciona para a página inicial após o login
        else:
            error_message = 'Credenciais inválidas. Tente novamente.'
            return render(request, 'finance_app/login.html', {'error_message': error_message})
    return render(request, 'finance_app/login.html')

def logout_view(request):
    logout(request)
    return redirect('/login') 

finance_app/templates/finance_app/includes/modal-confirm-delete.html
{% if earning %}
<!-- Modal earning -->
<div class="modal fade" id="modalDeleteEarning{{ earning.id }}" tabindex="-1"
    aria-labelledby="modalDeleteEarning{{ earning.id }}Label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalDeleteEarning{{ earning.id }}Label">Confirmar exclusão</h5>
            </div>
            <div class="modal-body">
                <p>Deseja realmente deletar '{{ earning.description }}'?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                <a href="{% url 'finance_app:deleteearnings' earning.id %}" class="btn btn-danger">Deletar</a>
            </div>
        </div>
    </div>
</div>
{% else %}
<!-- Modal expense -->
<div class="modal fade" id="modalDeleteExpense{{ expense.id }}" tabindex="-1"
    aria-labelledby="modalDeleteExpense{{ expense.id }}Label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalDeleteExpense{{ expense.id }}Label">Confirmar exclusão</h5>
            </div>
            <div class="modal-body">
                <p>Deseja realmente deletar '{{ expense.description }}'?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                <a href="{% url 'finance_app:deleteexpenses' expense.id %}" class="btn btn-danger">Deletar</a>
            </div>
        </div>
    </div>
</div>
{% endif %}

finance_app/templates/finance_app/includes/modal-index.html
<!-- modal revenue -->
<div class="modal fade" id="ModalRevenue" tabindex="-1" role="dialog" aria-labelledby="ModalLabelRevenue">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h6 class="modal-title-md" id="ModalLabelRevenue">Adicionar Receita</h6>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="container">
                    <div class="row mt-1 mb-3">
                        <div class="col">
                            <button type="button" class="btn btn-outline-success w-100" data-toggle="collapse"
                                data-target="#categoryToggle" aria-expanded="false" aria-controls="categoryToggle">
                                Adicionar / Remover Categorias
                            </button>
                        </div>
                    </div>
                    <div class="collapse mt-3 mb-3" id="categoryToggle">
                        <div class="row">
                            <div class="col">
                                <form action="{% url 'finance_app:createcategoryearnings' %}" method="post">
                                    {% csrf_token %}
                                    <label for="newCategory">Nova Categoria</label>
                                    <input type="text" class="form-control" id="newCategory"
                                        placeholder="Digite o nome da nova categoria" name="description" required>
                                    <button type="submit" class="btn btn-primary mt-2">Adicionar</button>
                                </form>
                            </div>
                            <div class="col">
                                <form action="{% url 'finance_app:deletecategoryearnings' %}" method="post">
                                    {% csrf_token %}
                                    <label for="deleteCategory">Excluir Categoria</label>
                                    <select class="form-control" id="deleteCategory" name="delete-category" required>
                                        {% for categoryearning in categoryearnings %}
                                        <option value="{{ categoryearning.id }}">{{ categoryearning.name }}</option>
                                        {% endfor %}
                                    </select>
                                    <button type="submit" class="btn btn-danger mt-2">Excluir</button>
                                </form>
                            </div>
                        </div>
                    </div>
                    <form action="{% url 'finance_app:createearnings' %}" method="post" id="form-revenue">
                        {% csrf_token %}
                        <div class="row form-group">
                            <div class="col">
                                <!-- Descrição -->
                                <label for="description">Descrição</label>
                                <input type="text" class="form-control" id="description" placeholder="Descrição"
                                    name="description" required>
                            </div>
                            <div class="col">
                                <!-- Valor -->
                                <label for="value">Valor</label>
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">R$</span>
                                    </div>
                                    <input type="text" class="form-control" id="value" placeholder="Valor" name="value"
                                        required>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <!-- Data -->
                                <label for="date">Data</label>
                                <input type="date" class="form-control" id="date" placeholder="Data" name="date"
                                    required>
                            </div>
                            <div class="col">
                                <!-- Recorrente -->
                                <label for="recurrent">Recorrente</label>
                                <select class="form-control" id="recurrent" name="recurrent">
                                    <option value="0">Não</option>
                                    <option value="1">Sim</option>
                                </select>
                            </div>
                            <div class="col">
                                <!-- Categoria -->
                                <label for="category">Categoria</label>
                                <select class="form-control" id="category" name="category" required>
                                    {% for categoryearning in categoryearnings %}
                                    <option value="{{ categoryearning.id }}">{{ categoryearning.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        <div class="row mt-3">
                            <div class="col">
                                <button type="submit" class="btn btn-primary w-100" id="submit-form">Salvar</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- modal expense -->
<div class="modal fade" id="ModalExpense" tabindex="-1" role="dialog" aria-labelledby="ModalLabelExpense">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h6 class="modal-title-md" id="ModalLabelExpense">Adicionar Despesa</h6>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="container">
                    <div class="row mt-1 mb-3">
                        <div class="col">
                            <button type="button" class="btn btn-outline-success w-100" data-toggle="collapse"
                                data-target="#categoryToggle" aria-expanded="false" aria-controls="categoryToggle">
                                Adicionar / Remover Categorias
                            </button>
                        </div>
                    </div>
                    <div class="collapse mt-3 mb-3" id="categoryToggle">
                        <div class="row">
                            <div class="col">
                                <form action="{% url 'finance_app:createcategoryexpenses' %}" method="post">
                                    {% csrf_token %}
                                    <label for="newCategory">Nova Categoria</label>
                                    <input type="text" class="form-control" id="newCategory" required
                                        placeholder="Digite o nome da nova categoria" name="description">
                                    <button type="submit" class="btn btn-primary mt-2">Adicionar</button>
                                </form>
                            </div>
                            <div class="col">
                                <form action="{% url 'finance_app:deletecategoryexpenses' %}" method="post">
                                    {% csrf_token %}
                                    <label for="deleteCategory">Excluir Categoria</label>
                                    <select class="form-control" id="deleteCategory" name="delete-category" required>
                                        {% for categoryexpense in categoryexpenses %}
                                        <option value="{{ categoryexpense.id }}">{{ categoryexpense.name }}</option>
                                        {% endfor %}
                                    </select>
                                    <button type="submit" class="btn btn-danger mt-2">Excluir</button>
                                </form>
                            </div>
                        </div>
                    </div>
                    <form action="{% url 'finance_app:createexpenses' %}" method="post" id="form-expense">
                        {% csrf_token %}
                        <div class="row form-group">
                            <div class="col">
                                <!-- Descrição -->
                                <label for="description">Descrição</label>
                                <input type="text" class="form-control" id="description" placeholder="Descrição"
                                    name="description" required>
                            </div>
                            <div class="col">
                                <!-- Valor -->
                                <label for="value">Valor</label>
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">R$</span>
                                    </div>
                                    <input type="text" class="form-control" id="value" placeholder="Valor" name="value">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <!-- Data -->
                                <label for="date">Data</label>
                                <input type="date" class="form-control" id="date" placeholder="Data" name="date"
                                    required>
                            </div>
                            <div class="col">
                                <!-- Expense recorrente -->
                                <label for="recurrent">Recorrente</label>
                                <select class="form-control" id="recurrent" name="recurrent">
                                    <option value="0">Não</option>
                                    <option value="1">Sim</option>
                                </select>
                            </div>
                            <div class="col">
                                <!-- Categoria -->
                                <label for="category">Categoria</label>
                                <select class="form-control" id="category" name="category" required>
                                    {% for categoryexpense in categoryexpenses %}
                                    <option value="{{ categoryexpense.id }}">{{ categoryexpense.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        <div class="row mt-3">
                            <div class="col">
                                <button type="submit" class="btn btn-primary w-100" id="submit-form">Salvar</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>